services:
  mariadb:
    image: bitnami/mariadb:latest
    container_name: mariadb
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_myapp
      - MARIADB_DATABASE=bitnami_myapp
    volumes:
      - ./mariadb_data:/bitnami/mariadb
    networks:
      - laravel-network

  laravel:
    image: bitnami/laravel:11.1.1
    depends_on:
      - mariadb
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_USERNAME=bn_myapp
      - DB_DATABASE=bitnami_myapp
    volumes:
      - ./web:/app
    networks:
      - laravel-network

networks:
  laravel-network:
    driver: bridge
